# Macro file for the initialization of abracadabra
# in interactive session
#
# Set some default verbose
/control/verbose 2
/control/saveHistory
/run/verbose 2

/abracadabra/spin_view false
/abracadabra/spin_speed 10

# Initialize kernel
/run/initialize
#
# Visualization setting
/control/execute macs/vis.mac
/vis/viewer/zoomTo 2.5
/abracadabra/verbosity 2 # will be overridden by setting in run macro
#/vis/viewer/zoomTo 40
#/vis/viewer/panTo 0.466 0
