# Model macro file for abracadabra

# Shared by interactive and batch mode

# Select detector geometry, generators and phantom here

/abracadabra/geometry both
/abracadabra/phantom nema_5
/abracadabra/nema5_sleeves 0
/abracadabra/detector imas
/abracadabra/cylinder_length 1000
/abracadabra/y_offset 0

/abracadabra/clear_pre_lxe false
/abracadabra/quartz_thickness 0
/abracadabra/xenon_thickness 20
