# Model macro file for abracadabra

# Shared by interactive and batch mode

# Select detector geometry, generators and phantom here

/abracadabra/geometry phantom
/abracadabra/phantom nema_4
/abracadabra/detector imas
/abracadabra/cylinder_length 1000

# When used as source of noise for NEMA 7
/abracadabra/z_offset 450

/abracadabra/steel_is_vacuum false
#/abracadabra/scintillator_thickness 50
/abracadabra/quartz_thickness  0
