/abracadabra/outfile "magic-nema5-dz=1m-LXe=40mm-noQrz-4.h5"
/abracadabra/event_number_offset 40000

/random/setSeeds 123456 987654

# Initialize kernel
/run/initialize

/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/abracadabra/print true

/attenuation_map/filename     attenuation-map.raw
/attenuation_map/full_widths  100 200 300
/attenuation_map/n_voxels     101 201 301
#/attenuation_map/generate

/run/beamOn 100
