/abracadabra/outfile "nema7-dz=1m-LXe=20mm-noQrz-5.h5"
/abracadabra/event_number_offset 1000000

/random/setSeeds 123456 987654

# Initialize kernel
/run/initialize

/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/abracadabra/verbosity 0

/attenuation_map/filename     nema7-density-map.raw
/attenuation_map/full_widths  220 220 200
/attenuation_map/n_voxels     151 151 151
#/attenuation_map/generate

/run/beamOn 1000000
