name: Install and Test
on:
  pull_request:
  push:
jobs:

  build-and-test:
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        py: [39]
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-22.11
      - uses: cachix/cachix-action@v12
        with:
          name: jacg-next-exp
          # If you chose API tokens for write access OR if you have a private cache
          authToken: '${{ secrets.CACHIX_JACG_NEXT_EXP }}'
      - name: Install dependencies via Nix
        run: nix-shell --argstr py ${{ matrix.py }}
      - name: Build
        run: nix-shell --argstr py ${{ matrix.py }} --run "just build"
      - name: Run tests
        run: nix-shell --argstr py ${{ matrix.py }} --run "just test-all --use-colour=yes"
